/*
 *
 * AnnouncementPage constants
 *
 */

export const DEFAULT_ACTION = 'app/AnnouncementPage/DEFAULT_ACTION';

export const FETCH_ANNOUNCEMENTS = 'app/AnnouncementPage/FETCH_ANNOUNCEMENTS';
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'app/AnnouncementPage/FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILED = 'app/AnnouncementPage/FETCH_ANNOUNCEMENTS_FAILED';

export const FETCH_ANNOUNCEMENT_CONTENT = 'app/AnnouncementPage/FETCH_ANNOUNCEMENT_CONTENT';
export const FETCH_ANNOUNCEMENT_CONTENT_SUCCESS = 'app/AnnouncementPage/FETCH_ANNOUNCEMENT_CONTENT_SUCCESS';
export const FETCH_ANNOUNCEMENT_CONTENT_FAILED = 'app/AnnouncementPage/FETCH_ANNOUNCEMENT_CONTENT_FAILED';
